# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

env:
  ENVIRONMENT: development
  D3_ADMIN_CREDENTIALS_PATH: admin-credentials.dev.yaml

includes:
  test: tasks/test.yml
  lint: tasks/lint.yml
  generate: tasks/generate.yml

tasks:
  default:
    desc: Run checks and tests
    deps:
      - lint
      - test
      - test:integration

  build:
    desc: Build the application
    sources:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    cmd: go build ./...

  run:
    desc: Run the application with hot reload
    cmd: go tool air
