# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

env:
  ENVIRONMENT: development

tasks:
  default:
    desc: Run checks and tests
    deps:
      - lint
      - test

  lint:
    desc: Run linting
    sources:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    cmd: golangci-lint run

  lint-fix:
    desc: Run linting
    sources:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    cmd: golangci-lint run --fix

  test:
    desc: Run tests
    cmd: ginkgo run

  build:
    desc: Build the application
    sources:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    cmd: go build ./...

  run:
    desc: Run the application with hot reload
    cmd: go tool air
