// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package atomicwriter_test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLocker creates a new instance of MockLocker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocker {
	mock := &MockLocker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLocker is an autogenerated mock type for the Locker type
type MockLocker struct {
	mock.Mock
}

type MockLocker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocker) EXPECT() *MockLocker_Expecter {
	return &MockLocker_Expecter{mock: &_m.Mock}
}

// Lock provides a mock function for the type MockLocker
func (_mock *MockLocker) Lock(ctx context.Context, key string) (context.Context, context.CancelFunc, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 context.Context
	var r1 context.CancelFunc
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (context.Context, context.CancelFunc, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) context.Context); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) context.CancelFunc); ok {
		r1 = returnFunc(ctx, key)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(context.CancelFunc)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockLocker_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type MockLocker_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockLocker_Expecter) Lock(ctx interface{}, key interface{}) *MockLocker_Lock_Call {
	return &MockLocker_Lock_Call{Call: _e.mock.On("Lock", ctx, key)}
}

func (_c *MockLocker_Lock_Call) Run(run func(ctx context.Context, key string)) *MockLocker_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLocker_Lock_Call) Return(context1 context.Context, cancelFunc context.CancelFunc, err error) *MockLocker_Lock_Call {
	_c.Call.Return(context1, cancelFunc, err)
	return _c
}

func (_c *MockLocker_Lock_Call) RunAndReturn(run func(ctx context.Context, key string) (context.Context, context.CancelFunc, error)) *MockLocker_Lock_Call {
	_c.Call.Return(run)
	return _c
}
